### ISSUE TITLE
En passant square not set when Loading position from FEN

### ISSUE THREAD

**Issue by tuxmania87** [rudzen/ChessLib#35]
When Loading position from FEN via Position.SetFen() the en passant square is not set properly

The expressions suggests if the 2nd character in the en passant part of FEN is 3,4,5, or 6 then its NOT an en passant square, when in fact such sqaures always end with 3 or 6.
`
chunk[1].InBetween('3', '6')
                    ? Square.None`

**Comment by rudzen** [comment]
Good catch.
