### ISSUE TITLE
Best way to implement shallow move scores.

### ISSUE THREAD

**Issue by digital-synapse** [rudzen/ChessLib#39]
In an effort to improve search performance I'm trying to implement a heuristic for alpha-beta pruning. It looks like the ExtMove structure supports this via the score member, but as far as I can tell GenerateMoves() will never set this to anything other than zero.

Can you offer any advice?
Is there a good way to extend generatemoves() so that moves are scored for example :
piecetaken * piecetakenvalue + pieceatrisk * pieceatriskvalue * .33

I was also interested in using perft but was unclear on exactly how to generate moves from the perft result.

**Comment by rudzen** [comment]
I did plan to implement a staged move selection based on _some_ heuristics. You can implement this yourself - for example by generating the known moves and then filtering them based on what information you have available in your engine.
Another option is to copy the move generator and add whatever functionality you might need.

The perft is basically only a move counting feature - so you cannot use the perft result for anything useful.

**Comment by digital-synapse** [comment]
I just wanted to say, Thanks for the info and all the great work on this
rules engine!
